# Views and Copies

In [22]:
import numpy as np

In [23]:
mi_casa = np.array([-45, -31, -12, 0, 2, 25, 51, 99])

In [24]:
su_casa = mi_casa

### Same or Different

In [26]:
mi_casa is su_casa and id(mi_casa) == id(su_casa)

True

In [27]:
mi_casa == su_casa

array([ True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

### View: a shallow copy

In [28]:
su_casa = mi_casa.view()
su_casa.shape = (2,4)
su_casa

array([[-45, -31, -12,   0],
       [  2,  25,  51,  99]])

In [29]:
mi_casa

array([-45, -31, -12,   0,   2,  25,  51,  99])

In [31]:
su_casa [0,3] = 12

In [32]:
mi_casa

array([-45, -31, -12,  12,   2,  25,  51,  99])

### Deep copy

In [35]:
su_casa = np.copy(mi_casa)
su_casa[3] = 7
su_casa

array([-45, -31, -12,   7,   2,  25,  51,  99])

In [36]:
mi_casa

array([-45, -31, -12,  12,   2,  25,  51,  99])