# Joining and Splitting arrays
- concatenate
- stack
- split

In [18]:
import numpy as np

### concatenate
documentation: http://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html

In [19]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
a

array([[1, 2],
       [3, 4]])

In [20]:
together = np.concatenate((a, b), axis=0)
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
together.shape

(3, 2)

In [22]:
together[1,1] = 555
together

array([[  1,   2],
       [  3, 555],
       [  5,   6]])

In [23]:
np.append(a,b, axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
a

array([[1, 2],
       [3, 4]])

In [31]:
c = np.array([[1, 2], [3, 4]]) *3 + 5
c

array([[ 8, 11],
       [14, 17]])

In [32]:
np.concatenate((a, c), axis=1)

array([[ 1,  2,  8, 11],
       [ 3,  4, 14, 17]])

In [33]:
np.hstack((a,c))

array([[ 1,  2,  8, 11],
       [ 3,  4, 14, 17]])

### stack

In [34]:
np.random.randn(3, 4)

array([[ 0.80033906,  0.00946912, -1.45239976,  0.41163408],
       [ 0.28660823,  0.18285557, -1.35851275, -0.95460554],
       [ 0.78435003,  0.22280464,  0.80832053,  0.23418303]])

In [36]:
arrays = np.zeros((5,3,4))
for n in range(5):
    arrays[n] = np.random.randn(3, 4)
    
arrays

array([[[ 0.31813982, -0.90657796, -0.11538679, -0.47445712],
        [-1.27806875,  0.18280239, -0.76431446, -0.42765571],
        [ 1.21731791, -1.10853736, -1.2165982 , -0.82581026]],

       [[-1.06251745,  0.79967149,  0.68371797,  0.20693526],
        [-0.04835136, -1.55296988, -0.31058398, -0.80098326],
        [ 1.50220642,  0.885221  ,  0.15798413,  0.85739   ]],

       [[-0.05618243, -0.51180351,  0.39332049,  0.64590556],
        [ 0.95621764, -1.05582974,  0.62120108,  1.47954256],
        [ 1.49438994,  0.35722555,  0.91419513, -0.11951521]],

       [[-0.50108481,  1.59265742,  0.71273564,  0.58722891],
        [-0.01369541, -1.58004573, -1.08667185,  2.11962448],
        [-0.09743789,  0.29439595, -0.50774845,  1.40605386]],

       [[ 1.90096313, -0.73491729,  0.81576807,  0.60997547],
        [ 0.48196876, -0.19906053,  2.14726489, -0.11417081],
        [-1.37571448, -0.42492804,  0.15373676,  1.07237163]]])

In [37]:
stack0 = np.stack(arrays, axis=0)
stack1 = np.stack(arrays, axis=1)
stack2 = np.stack(arrays, axis=2)

In [38]:
my_stacks = np.array([stack0.shape, stack1.shape, stack2.shape])
my_stacks

array([[5, 3, 4],
       [3, 5, 4],
       [3, 4, 5]])

In [39]:
stack0

array([[[ 0.31813982, -0.90657796, -0.11538679, -0.47445712],
        [-1.27806875,  0.18280239, -0.76431446, -0.42765571],
        [ 1.21731791, -1.10853736, -1.2165982 , -0.82581026]],

       [[-1.06251745,  0.79967149,  0.68371797,  0.20693526],
        [-0.04835136, -1.55296988, -0.31058398, -0.80098326],
        [ 1.50220642,  0.885221  ,  0.15798413,  0.85739   ]],

       [[-0.05618243, -0.51180351,  0.39332049,  0.64590556],
        [ 0.95621764, -1.05582974,  0.62120108,  1.47954256],
        [ 1.49438994,  0.35722555,  0.91419513, -0.11951521]],

       [[-0.50108481,  1.59265742,  0.71273564,  0.58722891],
        [-0.01369541, -1.58004573, -1.08667185,  2.11962448],
        [-0.09743789,  0.29439595, -0.50774845,  1.40605386]],

       [[ 1.90096313, -0.73491729,  0.81576807,  0.60997547],
        [ 0.48196876, -0.19906053,  2.14726489, -0.11417081],
        [-1.37571448, -0.42492804,  0.15373676,  1.07237163]]])

In [40]:
stack1

array([[[ 0.31813982, -0.90657796, -0.11538679, -0.47445712],
        [-1.06251745,  0.79967149,  0.68371797,  0.20693526],
        [-0.05618243, -0.51180351,  0.39332049,  0.64590556],
        [-0.50108481,  1.59265742,  0.71273564,  0.58722891],
        [ 1.90096313, -0.73491729,  0.81576807,  0.60997547]],

       [[-1.27806875,  0.18280239, -0.76431446, -0.42765571],
        [-0.04835136, -1.55296988, -0.31058398, -0.80098326],
        [ 0.95621764, -1.05582974,  0.62120108,  1.47954256],
        [-0.01369541, -1.58004573, -1.08667185,  2.11962448],
        [ 0.48196876, -0.19906053,  2.14726489, -0.11417081]],

       [[ 1.21731791, -1.10853736, -1.2165982 , -0.82581026],
        [ 1.50220642,  0.885221  ,  0.15798413,  0.85739   ],
        [ 1.49438994,  0.35722555,  0.91419513, -0.11951521],
        [-0.09743789,  0.29439595, -0.50774845,  1.40605386],
        [-1.37571448, -0.42492804,  0.15373676,  1.07237163]]])

In [41]:
stack2

array([[[ 0.31813982, -1.06251745, -0.05618243, -0.50108481,  1.90096313],
        [-0.90657796,  0.79967149, -0.51180351,  1.59265742, -0.73491729],
        [-0.11538679,  0.68371797,  0.39332049,  0.71273564,  0.81576807],
        [-0.47445712,  0.20693526,  0.64590556,  0.58722891,  0.60997547]],

       [[-1.27806875, -0.04835136,  0.95621764, -0.01369541,  0.48196876],
        [ 0.18280239, -1.55296988, -1.05582974, -1.58004573, -0.19906053],
        [-0.76431446, -0.31058398,  0.62120108, -1.08667185,  2.14726489],
        [-0.42765571, -0.80098326,  1.47954256,  2.11962448, -0.11417081]],

       [[ 1.21731791,  1.50220642,  1.49438994, -0.09743789, -1.37571448],
        [-1.10853736,  0.885221  ,  0.35722555,  0.29439595, -0.42492804],
        [-1.2165982 ,  0.15798413,  0.91419513, -0.50774845,  0.15373676],
        [-0.82581026,  0.85739   , -0.11951521,  1.40605386,  1.07237163]]])

### split
for information, please see: http://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html

In [42]:
temp = np.arange(5)
np.split(temp,1)

[array([0, 1, 2, 3, 4])]

In [43]:
before_split = stack0
before_split.shape

(5, 3, 4)

In [44]:
s0=np.split (before_split, 5, axis=0)
s0

[array([[[ 0.31813982, -0.90657796, -0.11538679, -0.47445712],
         [-1.27806875,  0.18280239, -0.76431446, -0.42765571],
         [ 1.21731791, -1.10853736, -1.2165982 , -0.82581026]]]),
 array([[[-1.06251745,  0.79967149,  0.68371797,  0.20693526],
         [-0.04835136, -1.55296988, -0.31058398, -0.80098326],
         [ 1.50220642,  0.885221  ,  0.15798413,  0.85739   ]]]),
 array([[[-0.05618243, -0.51180351,  0.39332049,  0.64590556],
         [ 0.95621764, -1.05582974,  0.62120108,  1.47954256],
         [ 1.49438994,  0.35722555,  0.91419513, -0.11951521]]]),
 array([[[-0.50108481,  1.59265742,  0.71273564,  0.58722891],
         [-0.01369541, -1.58004573, -1.08667185,  2.11962448],
         [-0.09743789,  0.29439595, -0.50774845,  1.40605386]]]),
 array([[[ 1.90096313, -0.73491729,  0.81576807,  0.60997547],
         [ 0.48196876, -0.19906053,  2.14726489, -0.11417081],
         [-1.37571448, -0.42492804,  0.15373676,  1.07237163]]])]

In [ ]:
type(s0)

In [ ]:
s0[1]

In [ ]:
s0[1].shape

In [ ]:
s1=np.split (before_split, 3, axis=1)
s1

In [ ]:
s2=np.split (before_split, 4, axis=2)
s2