# Finding Pattern

In [1]:
import numpy as np

## Given this array, find the next number in the sequence

In [2]:
my_teaser_array = np.array([1, 7, 19, 37, 61, 91, 127, 169, 217, 271, 331])
my_teaser_array

array([  1,   7,  19,  37,  61,  91, 127, 169, 217, 271, 331])

##### for information about numpy.diff, please see: http://docs.scipy.org/doc/numpy/reference/generated/numpy.diff.html

In [3]:
np.diff(my_teaser_array)

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60])

In [4]:
np.diff(my_teaser_array, n=2)

array([6, 6, 6, 6, 6, 6, 6, 6, 6])

In [5]:
np.diff(my_teaser_array, n=3)

array([0, 0, 0, 0, 0, 0, 0, 0])

##### Warning: imports should (usually) appear at top of notebook

If SymPy is not included on your computer; open a console and type 'conda sympy'

In [6]:
from sympy import init_session
init_session() 

IPython console for SymPy 1.0 (Python 3.6.1-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at http://docs.sympy.org/1.0/


In [7]:
diff(x**3)

In [8]:
diff(x**3, x, 2)

In [9]:
diff(x**3, x, 3)

In [10]:
diff(x**3, x, 4)

In [11]:
def my_guess(n):
    return (n+1)**3 - n**3

In [12]:
my_guess(np.arange(20))

array([   1,    7,   19,   37,   61,   91,  127,  169,  217,  271,  331,
        397,  469,  547,  631,  721,  817,  919, 1027, 1141])

In [13]:
my_teaser_array = np.array([1, 7, 19, 37, 61, 91, 127, 169, 217, 271, 331])
my_teaser_array

array([  1,   7,  19,  37,  61,  91, 127, 169, 217, 271, 331])